// Dados de isenção de IPVA para PCD por estado
// Gerado automaticamente a partir da pesquisa de normativas estaduais

export const estadosIPVAPCD = {
  "AC": {
    "nome": "Acre",
    "legislacao": "Lei Complementar nº 483, de 17 de dezembro de 2024, Art. 13, I",
    "teto_veiculo_novo": "R$ 100.000",
    "teto_veiculo_usado": "R$ 70.000",
    "deficiencias_aceitas": "Física, Visual, Mental severa ou profunda, Autismo",
    "aceita_nao_condutor": "Sim com condições",
    "orgao_responsavel": "SECRETARIA DA FAZENDA - SEFAZ",
    "documentos_exigidos": "1. Carteira de Identidade Física ou Digital (CIN) OU Carteira de Motorista Física ou Digital OU Carteira de Identidade Profissional (CREA, OAB, CRM e etc.) OU Passaporte, original e 01 cópia simples que ficará retida|2. CPF, original e 01 cópia que ficará retida (obrigatório caso não esteja registrado no documento de identificação)|3. Laudo da Perícia Médica atualizado, emitido pelo DETRAN, original e 01 cópia simples que ficará retida. No laudo deve conter o CID – Classificação Estatística Internacional de Doença e o tipo de deficiência e as adaptações do veículo (quando exigidos)|4. Contracheque OU Decore OU Holerite OU Declaração do Imposto de Renda OU Carteira de Trabalho com anotações sobre a renda, original e 01 cópia simples que ficará retida|5. Comprovante de endereço atualizado, original e 01 cópia simples que ficará retida OU Declaração de Endereço, original que ficará retida, obtida no atendimento|6. Certidão de Débitos Relativos a Créditos Tributários Federais e à Dívida Ativa da União, original|7. CRV – Certificado de Registro de Veículo, original e 01 cópia simples que ficará retida|8. Nota Fiscal, original e 01 cópia simples que ficará retida (obrigatório para veículos adquiridos a partir de 2021)",
    "passo_a_passo": "1. Reunir a documentação necessária (identidade, CPF, laudo médico do DETRAN, comprovante de renda, comprovante de endereço, certidão de débitos, CRV, Nota Fiscal do veículo).|2. Dirigir-se a um dos locais de atendimento: OCA - Rio Branco, OCA - Brasiléia ou Sefaz - Atendimento.|3. Apresentar a documentação para solicitar a isenção.",
    "link_oficial": "https://www.ac.gov.br/servico/ipva-isencao-pessoas-com-deficiencia",
    "sistema_protocolo": "Portal de Serviços do Estado do Acre",
    "link_protocolo": "https://acl.ac.gov.br/login/sistema?layout=cidadao&return=protocolo",
    "condicoes_nao_condutor": "Veículo deverá ser dirigido por condutor autorizado pelo requerente, conforme identificação constante do Anexo VI do Convênio ICMS nº 38/2012.",
    "tea_nao_condutor": "Sim com condições",
    "prazo_renovacao": "Não especificado na Lei Complementar nº 483/2024, mas o regulamento poderá dispor sobre a forma de sua renovação.",
    "observacoes": "A isenção aplica-se a um único veículo por beneficiário. É necessário comprovar renda de até 10 salários-mínimos. O veículo deve ser utilizado exclusivamente no transporte da pessoa com deficiência.",
    "fonte_consultada": "https://www.ac.gov.br/servico/ipva-isencao-pessoas-com-deficiencia|https://www.legisweb.com.br/legislacao/?legislacao=470621"
  },
  "AL": {
    "nome": "Alagoas",
    "legislacao": "Lei nº 6.555/2004, Convênio Nacional ICMS nº 38/2012, Convênio ICMS 64/2006, Lei Estadual nº 9.780/2025 (altera a Lei Estadual Nº 6555/2004)",
    "teto_veiculo_novo": "R$ 70.000",
    "teto_veiculo_usado": "Mesmo teto (R$ 70.000)",
    "deficiencias_aceitas": "Física, Visual, Mental (severa ou profunda), Síndrome de Down, Autista",
    "aceita_nao_condutor": "Sim com condições",
    "orgao_responsavel": "SEFAZ-AL",
    "documentos_exigidos": "Laudo de junta médica (SUS ou credenciado) | Requerimento de Isenção | Passo a Passo para Emissão da Taxa de Fiscalização - IPVA",
    "passo_a_passo": "1. Impostos → 2. IPVA → 3. Pedido de isenção → 1. Isenção do IPVA de veículo automotor destinado a pessoas com deficiência → 1. Iniciar atendimento. O requerimento é feito de forma virtual, através da atendente Nise, pelo site ou pelo Telegram (@nise_sefaz_al_bot), que filtra a demanda e encaminha para um servidor que abrirá o processo no Sistema Eletrônico de Informações (SEI). O cidadão pode acompanhar o andamento da solicitação no site de consulta pública do SEI.",
    "link_oficial": "https://www.sefaz.al.gov.br/114-nise/servicos-disponiveis-isencao-ipva",
    "sistema_protocolo": "SEI",
    "link_protocolo": "https://www.sefaz.al.gov.br/114-nise/servicos-disponiveis-isencao-ipva",
    "condicoes_nao_condutor": "Apresentar laudo de junta médica de unidade pública de Saúde ou instituição privada de saúde credenciada pelo SUS, que comprove a condição de deficiência.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Não especificado, mas a isenção é válida por quatro anos de posse do veículo.",
    "observacoes": "É necessário que o proprietário permaneça em posse do veículo por quatro anos. Caso contrário, as isenções concedidas serão cobradas com acréscimos de multa e atualização monetária, a partir da data de aquisição do veículo.",
    "fonte_consultada": "https://www.sefaz.al.gov.br/noticias/item/3557-governo-do-estado-concede-beneficio-de-ipva-para-20-da-frota-em-alagoas | https://www.sefaz.al.gov.br/114-nise/servicos-disponiveis-isencao-ipva | https://www.sefaz.al.gov.br/legislacao | https://alagoasdigital.al.gov.br/servico/1837"
  },
  "AP": {
    "nome": "Amapá",
    "legislacao": "Lei Estadual nº 3.152/2024, Art. 6º, IV",
    "teto_veiculo_novo": "R$ 120.000",
    "teto_veiculo_usado": "Mesmo teto (R$ 120.000), com isenção parcial para valores acima de R$ 70.000",
    "deficiencias_aceitas": "Física, Visual, Mental severa ou profunda, Síndrome de Down, Autismo, Doente renal crônico",
    "aceita_nao_condutor": "Sim com condições",
    "orgao_responsavel": "Secretaria de Estado da Fazenda (SEFAZ/AP)",
    "documentos_exigidos": "1. Requerimento padrão SEFAZ | 2. Taxa de serviços (R$ 50,00 - código 5004/2209) | 3. RG e CPF | 4. CNH (se houver) | 5. Comprovante de endereço | 6. Laudo médico do SUS",
    "passo_a_passo": "1. Acessar o site da SEFAZ Amapá (www.sefaz.ap.gov.br) | 2. Procurar pela opção de solicitação de isenção de IPVA para PCD | 3. Preencher o requerimento online ou baixar o formulário padrão | 4. Anexar a documentação exigida | 5. Pagar a taxa de serviço | 6. Protocolar o pedido online ou presencialmente em uma unidade de atendimento da SEFAZ.",
    "link_oficial": "https://www.sefaz.ap.gov.br/",
    "sistema_protocolo": "Portal de Serviços do Amapá",
    "link_protocolo": "https://apdigital.portal.ap.gov.br/",
    "condicoes_nao_condutor": "Identificação de até três condutores autorizados.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "A isenção deve ser renovada anualmente, conforme a Instrução Normativa SEFAZ/GAB Nº 2/2025 que trata do cálculo proporcional nas renovações.",
    "observacoes": "A isenção para veículos usados com valor venal entre R$ 70.000,01 e R$ 100.000,00 é parcial, com o IPVA incidindo sobre o valor que excede os R$ 70.000,00. Acima de R$ 100.000,00, o imposto é integral.",
    "fonte_consultada": "Lei Estadual nº 3.152/2024; Decreto Estadual nº 007/2013; Portaria 'T' SEFAZ Nº 30/2025; Instrução Normativa SEFAZ/GAB Nº 2/2025; Portal LegisWeb (www.legisweb.com.br)"
  },
  "AM": {
    "nome": "Amazonas",
    "legislacao": "Lei nº 4.719, art. 10-A; Decreto nº 53.497/2026",
    "teto_veiculo_novo": "Sem limite",
    "teto_veiculo_usado": "Mesmo teto",
    "deficiencias_aceitas": "Física, Visual, Mental severa ou profunda, Autismo",
    "aceita_nao_condutor": "Sim",
    "orgao_responsavel": "SEFAZ-AM",
    "documentos_exigidos": "1. Requerimento | 2. LAUDO MÉDICO | 3. Documento de Identificação da PCD (RG, CPF, etc.) | 4. Comprovante de residência da PCD | 5. Carteira Nacional de Habilitação - CNH (se condutor) | 6. Comprovante de residência do Responsável pela PCD (se aplicável) | 7. Certidão Negativa de Débito | 8. CRLV | 9. Declaração de Veracidade | 10. Documento Comprobatório de Responsabilidade Legal (Certidão de Nascimento, Guarda, decisão judicial, Tutela/Curatela ou Decisão Apoiada)",
    "passo_a_passo": "1. Acessar o serviço online ou presencialmente. | 2. Preencher o requerimento. | 3. Apresentar a documentação necessária, incluindo laudo médico e documentos de identificação. | 4. Aguardar a análise do pedido pela SEFAZ-AM.",
    "link_oficial": "https://www.sefaz.am.gov.br/portfolio-servicos/detalhes/1082",
    "sistema_protocolo": "Protocolo Virtual",
    "link_protocolo": "https://protocolovirtual.amazonas.am.gov.br/index.asp?tipo=AGENDAMENTO&idProcuracao=&assunto=20090",
    "condicoes_nao_condutor": "O veículo pode ser conduzido por um representante legal.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Anual, com antecedência mínima de 15 dias antes do vencimento do imposto.",
    "observacoes": "O benefício é válido para apenas um veículo por responsável. Não se aplica a veículos registrados diretamente no nome da pessoa com deficiência ou autismo. Em caso de transferência de titularidade, o benefício é cessado e o imposto deve ser recolhido proporcionalmente.",
    "fonte_consultada": "https://www.sefaz.am.gov.br/portfolio-servicos/detalhes/1082"
  },
  "BA": {
    "nome": "Bahia",
    "legislacao": "Convênio ICMS 38/12",
    "teto_veiculo_novo": "Não especificado na fonte consultada",
    "teto_veiculo_usado": "Não especificado na fonte consultada",
    "deficiencias_aceitas": "Física, Visual, Mental, Autismo (conforme Anexos II, III, III-A e IV do Conv. ICMS 38/12)",
    "aceita_nao_condutor": "Sim com condições",
    "orgao_responsavel": "Secretaria da Fazenda do Estado da Bahia - SEFAZ",
    "documentos_exigidos": "1. Requerimento a ser preenchido na PLATAFORMA BA.GOV.BR|2. Laudo pericial ou laudo de avaliação, conforme a deficiência, na forma dos Anexos II, III, III-A e IV do Conv. ICMS 38/12, emitido por entidades públicas ou privadas credenciadas ou por profissionais credenciados indicados pelo DETRAN (para laudo pericial - anexo II), ou prestador de serviço público de saúde ou serviço privado de saúde, contratado ou conveniado, que integre o Sistema Único de Saúde (SUS) (para laudo de avaliação - anexos III, III-A e IV)|3. Nota Fiscal de aquisição do veículo se carro novo, ou CRLV, se usado, em nome do PcD|4. Documentos Pessoais: Carteira Nacional de Habilitação (se condutor) ou RG, CPF (se não condutor)|5. Para veículos não cadastrados no Detran, apresentar Requisição de Serviço do DETRAN constando a Placa|6. Relação dos condutores autorizados quando o requerente não for o condutor do veículo, na forma do Anexo VI do Convênio ICMS nº 38/12|7. Comprovante de residência do interessado (PcD) e ou dos condutores autorizados, quando aplicável|8. Carteira Nacional de Habilitação de todos os condutores autorizados de que trata os §§ 4º e 5º, da cláusula segunda, do Convênio ICMS 38/12, caso seja feita a indicação na forma do § 5º da cláusula|9. Procuração e Documento de identificação, se Procurador",
    "passo_a_passo": "1. Acessar a PLATAFORMA BA.GOV.BR, clicando no link disponível no Canal WEB|2. Possuir senha na PLATAFORMA BA.GOV.BR ou no PORTAL GOV.BR e efetuar o login|3. Localizar o serviço 'Solicitar isenção de IPVA para veículos destinados à pessoa com deficiência (PcD)'|4. Clicar em 'solicitar'|5. Seguir as instruções e clicar em 'continuar'|6. Indicar se o requerimento será feito pelo próprio requerente ou pelo seu procurador|7. Preencher os dados do requerente|8. Conferir os dados do requerente e clicar em 'registrar solicitação'|9. Inserir e enviar os arquivos referentes aos documentos necessários relacionados no item anterior",
    "link_oficial": "https://www.ba.gov.br/servico/sefaz/solicitar-isencao-de-ipva-para-veiculos-destinados-a-pessoa-com-deficiencia-pcd",
    "sistema_protocolo": "PLATAFORMA BA.GOV.BR",
    "link_protocolo": "https://www.ba.gov.br/servico/sefaz/solicitar-isencao-de-ipva-para-veiculos-destinados-a-pessoa-com-deficiencia-pcd",
    "condicoes_nao_condutor": "Indicar até 3 condutores autorizados; condutores devem comprovar residência na mesma localidade do beneficiário.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Não especificado na fonte consultada",
    "observacoes": "Todos os documentos deverão estar digitalizados em formato “pdf”, separadamente e nomeados de acordo o conteúdo, sendo que, caso não use scanner de mesa, deverá enquadrar o documento, preservando as bordas, com o documento na vertical com a parte de cima do documento coincidindo com a parte superior do original, observando a qualidade das cópias, tendo em vista que o processo com documentos não legíveis será indeferido de plano.",
    "fonte_consultada": "https://www.ba.gov.br/servico/sefaz/solicitar-isencao-de-ipva-para-veiculos-destinados-a-pessoa-com-deficiencia-pcd"
  },
  "CE": {
    "nome": "Ceará",
    "legislacao": "Lei nº 15.066/2011 (altera a Lei nº 12.023/1992), Instrução Normativa nº 04/2012, Decreto nº 22.311/1992",
    "teto_veiculo_novo": "R$ 157.468,00",
    "teto_veiculo_usado": "Não se aplica",
    "deficiencias_aceitas": "Física, Visual, Mental severa ou profunda, Autismo",
    "aceita_nao_condutor": "Sim com condições",
    "orgao_responsavel": "Secretaria da Fazenda do Ceará (SEFAZ-CE)",
    "documentos_exigidos": "1. Formulário padrão preenchido (Anexo Único da Instrução Normativa nº 04/2012) | 2. Cópias do RG, CPF, CNH e CRLV do veículo | 3. Laudo médico | 4. Certidão original do registro de interdição (se aplicável)",
    "passo_a_passo": "A solicitação deve ser feita anualmente junto às Células de Execução da Administração Tributária (CEXAT) ou ao Núcleo de Atendimento (NUAT).",
    "link_oficial": "https://servicos.sefaz.ce.gov.br/internet/ipva/gerados/isencao_imposto.asp",
    "sistema_protocolo": "Sistema Tramita",
    "link_protocolo": "https://contribuinte-tramita.apps.sefaz.ce.gov.br/",
    "condicoes_nao_condutor": "Indicar até 3 condutores autorizados, com possibilidade de substituição, desde que o condutor substituto comprove residência no mesmo município do beneficiário.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Anual",
    "observacoes": "A isenção é limitada a um único veículo por proprietário. O veículo deve ser de procedência nacional.",
    "fonte_consultada": "https://servicos.sefaz.ce.gov.br/internet/ipva/gerados/isencao_imposto.asp"
  },
  "DF": {
    "nome": "Distrito Federal",
    "legislacao": "Lei nº 6.466/2019, alterada pela Lei nº 7.591/2024",
    "teto_veiculo_novo": "Sem limite",
    "teto_veiculo_usado": "Não se aplica",
    "deficiencias_aceitas": "Física, Visual, Mental severa ou profunda, Síndrome de Down, Autismo",
    "aceita_nao_condutor": "Sim com condições",
    "orgao_responsavel": "Secretaria de Estado de Economia do Distrito Federal (SEEC/DF)",
    "documentos_exigidos": "1. Ato de nomeação do curador, se for o caso | 2. Cópia da carteira de identidade, em caso de beneficiário menor de idade ou interdito | 3. Declaração de Serviço Médico Privado Integrante do Sistema Único de Saúde – SUS, se for o caso | 4. Certidão Negativa de Débitos relativos à Dívida Ativa do Distrito Federal | 5. Laudo/formulário médico específico para cada deficiência",
    "passo_a_passo": "1. Acessar o Atendimento Virtual da SEEC/DF | 2. Escolher Menu Pessoa Física > Todos os Serviços > Assunto “IPVA” > Tipo de Atendimento “Pessoa com Deficiência – Solicitar Isenção IPVA – serviço” | 3. Anexar a documentação exigida",
    "link_oficial": "https://www2.agencianet.fazenda.df.gov.br/Atendimento/SAC#/Home",
    "sistema_protocolo": "Atendimento Virtual",
    "link_protocolo": "https://www2.agencianet.fazenda.df.gov.br/Atendimento/SAC#/Home",
    "condicoes_nao_condutor": "O veículo automotor deverá ser adquirido diretamente pelo portador da deficiência física e, no caso do interdito, pelo curador. O curador responde solidariamente.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Não encontrado",
    "observacoes": "A Lei nº 7.591/2024, que alterou a Lei nº 6.466/2019, ampliou o rol de deficiências e revogou o teto de R$ 70.000, mas não estabeleceu um novo teto. A informação sobre o teto de R$ 200.000 não foi encontrada na legislação consultada.",
    "fonte_consultada": "https://www.legisweb.com.br/legislacao/?id=469915, https://sepd.df.gov.br/w/isencao-de-ipva-para-pessoas-com-deficiencia"
  },
  "ES": {
    "nome": "Espírito Santo",
    "legislacao": "Decreto nº 5458-R, de 27 de julho de 2023",
    "teto_veiculo_novo": "R$ 100.000",
    "teto_veiculo_usado": "R$ 100.000",
    "deficiencias_aceitas": "Física, Auditiva, Visual, Mental severa ou profunda, Autismo, Síndrome de Down",
    "aceita_nao_condutor": "Sim",
    "orgao_responsavel": "SEFAZ-ES (Agência da Receita Estadual)",
    "documentos_exigidos": "1. Laudo pericial fornecido por médico do Sistema Único de Saúde – SUS, especificando o tipo de deficiência | 2. Requerimento de Reconhecimento de Isenção de IPVA.",
    "passo_a_passo": "1. Acessar o Sistema de Gestão de Documentos Eletrônicos do Estado (e-Docs) | 2. Preencher o requerimento de isenção | 3. Anexar o laudo pericial do SUS | 4. Enviar à Agência da Receita Estadual da circunscrição do interessado.",
    "link_oficial": "https://sefaz.es.gov.br/isencao-de-ipva",
    "sistema_protocolo": "e-Docs",
    "link_protocolo": "https://guiadeservicos.es.gov.br/Servicos/Detalhes/2604",
    "condicoes_nao_condutor": "Documento que comprove a responsabilidade (certidão de nascimento ou carteira de identidade do portador de deficiência), a tutela, ou certidão judicial de curatela, se for o caso, nos termos do Código Civil.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Permanente (enquanto o proprietário estiver com o veículo)",
    "observacoes": "O processo de solicitação é feito por meio do Sistema de Gestão de Documentos Eletrônicos do Estado (e-Docs), sem necessidade de comparecer a uma Agência da Receita Estadual. O teto de R$ 100.000 se aplica tanto para ICMS quanto para IPVA. O benefício é restrito a um veículo por beneficiário.",
    "fonte_consultada": "http://www2.sefaz.es.gov.br/LegislacaoOnline/lpext.dll/infobaselegislacaoonline/decretos/2023/dec5458-r.htm?fn=document-frame.htm&f=templates&2.0 | https://detran.es.gov.br/Not%C3%ADcia/decreto-simplifica-processos-e-amplia-isencao-de-ipva-para-pessoa-com-deficiencia | https://gringo.com.vc/blog/isencao-do-ipva-es/ | https://www.agazeta.com.br/motor/pcd-saiba-como-ter-isencao-de-ipva-em-carro-zero-seminovos-ou-usado-no-es-0224"
  },
  "GO": {
    "nome": "Goiás",
    "legislacao": "Lei 11.651 de 26 de dezembro de 1991, art. 94, inciso IV e § 9°, Código Tributário do Estado do Goiás – CTE. Projeto de Lei nº 334/2022 (aguardando sanção governamental)",
    "teto_veiculo_novo": "R$ 140.000 (isenção total até R$ 70.000, isenção parcial de R$ 70.000 a R$ 140.000)",
    "teto_veiculo_usado": "Não se aplica (o teto de R$ 140.000 é para veículos 0km)",
    "deficiencias_aceitas": "Física, Visual, Mental severa ou profunda, Autismo/TEA",
    "aceita_nao_condutor": "Sim com condições",
    "orgao_responsavel": "Secretaria da Economia de Goiás (SEFAZ-GO)",
    "documentos_exigidos": "1. Documento de Identidade com foto e CPF (RG)|2. Comprovante de endereço|3. CNH com observações conforme Anexo II da Resolução Contran nº 886/21 (para condutor)|4. Laudo de Perícia Médica do DETRAN com a portaria de designação da junta médica (para condutor)|5. Exame Prático de Direção Veicular, se o Laudo tiver esta determinação (para condutor)|6. CRLV do veículo|7. Nota fiscal referente à colocação do acessório ou da adaptação efetuada pela oficina especializada ou pela concessionária autorizada e o laudo relativo à vistoria do veículo fornecido pelo DETRAN/GO, caso o veículo não tenha saído de fábrica com as características específicas discriminadas no laudo médico apresentado (para condutor)|8. Laudo Médico – Apêndice XXXVIII (para não-condutor)|9. Declaração que o emissor do laudo integra o SUS – Apêndice XL (para não-condutor)|10. Formulário de Autorização dos Condutores – Apêndice XLI (para não-condutor)|11. CNH e Documento de Identificação (RG) do Condutor 1 (para não-condutor)|12. CNH e Documento de Identificação (RG) do Condutor 2 (para não-condutor)|13. CNH e Documento de Identificação (RG) do Condutor 3 (para não-condutor)|14. Comprovante de endereço Condutor 1 (no mesmo município do interessado) (para não-condutor)|15. Comprovante de endereço Condutor 2 (no mesmo município do interessado) (para não-condutor)|16. Comprovante de endereço Condutor 3 (no mesmo município do interessado) (para não-condutor)|17. Laudo de avaliação deficiência mental severa ou profunda (anexo VII da Instrução Normativa RFB nº 1769, de 18 de dezembro de 2017) (para não-condutor)|18. Procuração ou certidão de nascimento para menor de idade; curatela, etc. (se aplicável)|19. Documentação pessoal do procurador/responsável (documento de identidade com foto e CPF e comprovante de endereço) (se aplicável)",
    "passo_a_passo": "1. Realizar a solicitação exclusivamente na Plataforma Digital de Processos – PDP|2. Selecionar se o serviço é para você ou outro: (Para MIM / Sou Procurador)|3. Selecionar o tipo: ISENÇÕES PARA PCD|4. Selecionar o subtipo: ISENÇÃO DE IPVA – DEFICIENTE FÍSICO CONDUTOR ou ISENÇÃO DE IPVA – DEFICIENTE MENTAL NÃO CONDUTOR (conforme o caso)|5. Baixar o formulário de requerimento disponibilizado na plataforma, preencher e assinar (com certificado digital ou impresso e digitalizado em PDF colorido)|6. Fazer o upload do formulário preenchido e assinado|7. Fazer o upload dos documentos requisitados em cada caixinha, e nas sinalizadas com asterisco (*) os documentos são obrigatórios|8. Se o processo for deferido, o solicitante receberá um COMUNICADO pelo sistema PDP com uma cópia do Ato Declaratório que reconhece a isenção do IPVA do veículo.",
    "link_oficial": "https://goias.gov.br/economia/ipva/",
    "sistema_protocolo": "Plataforma Digital de Processos – PDP",
    "link_protocolo": "https://goias.gov.br/economia/plataforma-digital-de-processos/",
    "condicoes_nao_condutor": "É necessário o Formulário de Autorização dos Condutores – Apêndice XLI e a CNH e Documento de Identificação (RG) de até 3 condutores, além do comprovante de endereço de cada condutor (no mesmo município do interessado).",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Permanente, enquanto o veículo estiver na propriedade do beneficiário.",
    "observacoes": "O benefício é exclusivo do beneficiário e não é transmitido aos herdeiros em caso de falecimento. A isenção perdura enquanto o veículo estiver na propriedade do beneficiário. A alienação (transferência) cessa o direito à isenção e deve ser comunicada via PDP.",
    "fonte_consultada": "https://goias.gov.br/economia/como-solicitar-a-isencao-de-ipva-para-veiculo-de-pessoa-portadora-de-deficiencia-fisica-condutor/ | https://goias.gov.br/economia/como-solicitar-a-isencao-de-ipva-para-veiculo-para-pessoa-portadora-de-deficiencia-mental-nao-condutor/ | https://portal.al.go.leg.br/noticias/155869/projeto-de-charles-bento-amplia-beneficio-fiscal-para-pessoas-com-deficiencia-e-autismo-em-goias"
  },
  "MA": {
    "nome": "Maranhão",
    "legislacao": "Resolução Administrativa Nº 3 de 26/01/2024, que altera o Anexo 1.2 do Regulamento do ICMS (Decreto 19.714/2003) com base no Convênio ICMS 38/12.",
    "teto_veiculo_novo": "R$ 120.000",
    "teto_veiculo_usado": "Mesmo teto",
    "deficiencias_aceitas": "Física, Visual, Mental severa ou profunda, Síndrome de Down, Autismo",
    "aceita_nao_condutor": "Sim",
    "orgao_responsavel": "Secretaria de Estado da Fazenda (SEFAZ-MA)",
    "documentos_exigidos": "1. Documento de Identificação Oficial | 2. CPF | 3. Comprovante de Residência | 4. Laudo Médico Pericial | 5. CNH (se condutor) | 6. Documentos do veículo (CRV/CRLV) | 7. Nota Fiscal de aquisição do veículo",
    "passo_a_passo": "1. Reunir toda a documentação exigida em formato digital (PDF). | 2. Acessar o sistema online de solicitação de benefícios fiscais da SEFAZ-MA (atualmente indisponível). | 3. Preencher o formulário de solicitação com os dados do requerente e do veículo. | 4. Anexar os documentos digitalizados. | 5. Protocolar o pedido e aguardar a análise da SEFAZ-MA.",
    "link_oficial": "Os portais oficiais (sefaz.ma.gov.br) apresentaram instabilidade e não foi possível obter um link direto para o serviço de solicitação online.",
    "sistema_protocolo": "SEFAZNET",
    "link_protocolo": "https://sefaznet.sefaz.ma.gov.br/sefaznet/login.do?method=prepareLogin",
    "condicoes_nao_condutor": "Sim, com indicação de até 3 (três) condutores autorizados.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "A legislação menciona a prorrogação do benefício até 30 de abril de 2026, indicando a necessidade de renovação, mas a frequência exata não foi encontrada.",
    "observacoes": "A isenção para veículos novos de R$ 70.001 a R$ 120.000 é parcial, aplicada somente sobre o valor de R$ 70.000. A legislação encontrada refere-se principalmente ao ICMS, mas é a base para a isenção do IPVA, sendo aplicada de forma análoga.",
    "fonte_consultada": "Resolução Administrativa Nº 3 de 26/01/2024 (DOE-MA 05/02/2024), Convênio ICMS 38/12"
  },
  "MT": {
    "nome": "Mato Grosso",
    "legislacao": "Lei nº 7.301, de 17 de julho de 2000, Art. 7º, III e Portaria SEFAZ Nº 101, de 30 de julho de 2025 (que altera a Portaria SEFAZ Nº 125/2020)",
    "teto_veiculo_novo": "R$ 120.000",
    "teto_veiculo_usado": "Mesmo teto (R$ 120.000)",
    "deficiencias_aceitas": "Física (paraplegia, paraparesia, monoplagia, monoparesia, tetraplegia, tetraparesia, triplegia, hemiplegia, hemiparesia, amputação ou ausência de membro, paralisia cerebral, membros com deformidade congênita ou adquirida), Visual, Mental severa ou profunda, Autismo, Auditiva",
    "aceita_nao_condutor": "Sim com condições",
    "orgao_responsavel": "SEFAZ-MT (Coordenadoria de IPVA da Superintendência de Atendimento ao Contribuinte - CIPVA/SAC)",
    "documentos_exigidos": "1. Requerimento padrão (Formulário 1) | 2. Declaração de que não possui outro veículo com o benefício | 3. Declaração de que o uso do veículo se restringe às finalidades essenciais do beneficiário | 4. Cédula de Identidade (RG) e do Cartão do CPF ou do CNPJ | 5. Cópia da Carteira Nacional de Habilitação (CNH) do interessado ou do terceiro condutor | 6. Cópia do Certificado de Registro e Licenciamento de Veículo (CRLV) do exercício anterior | 7. Cópia do Certificado de Registro de Veículo (frente e verso) | 8. Cópia do documento fiscal de aquisição (Nota Fiscal) | 9. Certidão referente a pendências tributárias e não tributárias controladas pela SEFAZ/MT | 10. Laudo de perícia médica expedida pelo DETRAN/MT, atestando a incapacidade para dirigir e o tipo de deficiência e adaptações necessárias (Art. 6º da Portaria nº 100/2001-SEFAZ/MT)",
    "passo_a_passo": "1. Formalizar o interesse pelo reconhecimento da isenção de IPVA no pedido de isenção de ICMS (para veículos novos) | 2. Declarar que o uso do veículo se restringe às finalidades essenciais do beneficiário | 3. Comprovar regularidade fiscal estadual | 4. Atender aos requisitos e condições previstos para reconhecimento da isenção de ICMS | 5. Apresentar a documentação exigida (conforme lista acima) | 6. Para veículos usados, ingressar com requerimento específico para reconhecimento da isenção de IPVA",
    "link_oficial": "www.sefaz.mt.gov.br",
    "sistema_protocolo": "e-Process",
    "link_protocolo": "https://www.sefaz.mt.gov.br/eprocess/util/ViewMenuEProcessModAberto.jsp",
    "condicoes_nao_condutor": "A isenção é para pessoa com deficiência física condutora ou conduzida, pessoa com deficiência visual ou auditiva, pessoa com deficiência mental severa ou profunda, ou autista, conduzido por seu representante legal. Limitado a 1 veículo por proprietário.",
    "tea_nao_condutor": "Sim com condições",
    "prazo_renovacao": "Não especificado, mas a isenção é vinculada ao veículo e à condição do beneficiário, podendo cessar se o motivo ou a condição que lhe der causa cessar (Lei nº 7.301/2000, Art. 7º, § 1º)",
    "observacoes": "A isenção de IPVA é concedida automaticamente para o mesmo veículo ao ter o pedido de isenção de ICMS aprovado. Para veículos usados, é necessário um requerimento específico. A isenção é limitada a um veículo por proprietário.",
    "fonte_consultada": "https://www.legisweb.com.br/legislacao/?legislacao=131691 | https://www.legisweb.com.br/legislacao/?legislacao=481995 | https://www5.sefaz.mt.gov.br/w/sefaz-simplifica-isen%C3%A7%C3%A3o-de-ipva-para-pcd-e-taxistas-em-mato-grosso | https://www.legisweb.com.br/noticia/?id=28414"
  },
  "MS": {
    "nome": "Mato Grosso do Sul",
    "legislacao": "Decreto Nº 16.562 DE 06/02/2025, Art. 1º e Art. 2º; Lei nº 1.810, de 22 de dezembro de 1997, Art. 154",
    "teto_veiculo_novo": "Sem limite",
    "teto_veiculo_usado": "Sem limite",
    "deficiencias_aceitas": "Física, Visual, Mental severa ou profunda, Transtorno do Espectro Autista (TEA), Síndrome de Down, Múltipla",
    "aceita_nao_condutor": "Sim com condições (veículo pode estar registrado em nome da PCD ou de seu representante legal)",
    "orgao_responsavel": "SEFAZ-MS (Secretaria de Estado de Fazenda de Mato Grosso do Sul)",
    "documentos_exigidos": "1. Cópia do Laudo do Detran-MS que declara a deficiência do requerente ou; | 2. Cópia de atestados do SUS ou entidades conveniadas com o SUS (Postos de Saúde do Estado ou Prefeitura), com deficiência declarada por escrito ou; | 3. Cópia do Certificado de Registro e Licenciamento de Veículo (CRLV) ou da Nota Fiscal Eletrônica do veículo que deve estar em nome da pessoa com deficiência.",
    "passo_a_passo": "1. Acessar o Portal ICMS Transparente; | 2. Protocolar o requerimento por meio do Sistema de Solicitação de Abertura de Protocolo (SAP); | 3. Acessar a aba “Acesso Restrito” e entrar na conta ou fazer o cadastro.",
    "link_oficial": "https://www.sefaz.ms.gov.br/servicos-em-destaque/ipva-reducao-para-pessoa-com-deficiencia-pcd/",
    "sistema_protocolo": "e-SAP (via Portal e-Fazenda)",
    "link_protocolo": "https://eservicos.sefaz.ms.gov.br/",
    "condicoes_nao_condutor": "Veículo pode estar registrado em nome da pessoa com deficiência ou de seu representante legal.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Permanente, se a deficiência for considerada permanente. Em caso de troca de veículo, é necessário solicitar a transferência do benefício.",
    "observacoes": "O benefício concedido é uma redução de 60% do IPVA, e não uma isenção total. Limita-se a um veículo por PCD. Se a deficiência for permanente, a comprovação é única, exceto para representação legal ao atingir a maioridade. Não há teto de valor para a redução do IPVA.",
    "fonte_consultada": "https://www.sefaz.ms.gov.br/servicos-em-destaque/ipva-reducao-para-pessoa-com-deficiencia-pcd/ | https://www.legisweb.com.br/legislacao/?legislacao=473073 | https://www.despachantedok.com.br/blog/ipva/isencao-ipva-ms/"
  },
  "MG": {
    "nome": "Minas Gerais",
    "legislacao": "Decreto 43.709/03, Artigos 7º e 8º e Decreto 48.744/2023",
    "teto_veiculo_novo": "R$ 120.000",
    "teto_veiculo_usado": "Mesmo teto (R$ 120.000)",
    "deficiencias_aceitas": "Física, Visual, Mental severa ou profunda, Síndrome de Down, Autismo",
    "aceita_nao_condutor": "Sim com condições (indicação de condutor autorizado)",
    "orgao_responsavel": "Secretaria de Estado de Fazenda - SEF/MG",
    "documentos_exigidos": "Pessoa física: cópia dos documentos de identidade e CPF | Representado: documentos de identidade e CPF do representado e procuração (original ou cópia), cópia dos documentos de identidade e CPF do procurador | Veículo novo: Cópia da Nota fiscal (DANFE) | Veículo usado: cópia do recibo de transferência preenchido, datado, assinado e com reconhecimento de firma no cartório ou o CRLV | Laudo da perícia médica fornecido pela Comissão de Exames Especiais para Pessoas com Deficiência Física do CET-DETRAN-MG (para condutores) | Carteira Nacional de Habilitação (CNH) (para condutores) | Laudo de avaliação original emitido por equipe médica (para não condutores) | Declaração de Serviço Médico Privado Integrante do Sistema Único de Saúde (se aplicável) | Formulário de Identificação do Condutor Autorizado e cópias das CNHs dos condutores autorizados (para não condutores) | Documento que comprove a condição de responsável legal (pais, tutor, curador), se for o caso | Comprovante de residência dos condutores autorizados, emitidos no máximo, há 3 meses da data do requerimento de isenção",
    "passo_a_passo": "1. Clicar no SIARE para ser exibida página para preenchimento da solicitação | 2. Preencher na ABA ISENÇÃO os campos identificação do requerente, dados do endereço, dados de contato e dados da isenção | 3. Preencher na ABA VEÍCULOS a placa, renavam e chassi no caso de veículo usado | 4. Após a confirmação do pedido, o sistema exibe para a pessoa interessada o número de protocolo e de senha para acompanhamento da solicitação pelo sistema da SEF e também a relação dos documentos necessários para a análise do pedido | 5. Ao clicar em \"Imprimir Comprovante de Protocolo\" o sistema exibe o comprovante em PDF | 6. Os documentos devem ser digitalizados e anexados no requerimento de isenção no SIARE. A anexação de documentos pode ser realizada no momento em que você efetiva a solicitação ou posteriormente, acessando o SIARE com o número de protocolo, usuário e senha informados no e-mail enviado pela SEF confirmando a solicitação.",
    "link_oficial": "https://www2.fazenda.mg.gov.br/sol/ctrl/SOL/SERVWEB/CADASTRO_001?ACAO=VISUALIZAR",
    "sistema_protocolo": "SIARE",
    "link_protocolo": "https://www2.fazenda.mg.gov.br/sol/ctrl/SOL/SERVWEB/CADASTRO_001?ACAO=VISUALIZAR",
    "condicoes_nao_condutor": "Indicar condutor autorizado através de formulário específico (06.04.53) e apresentar cópias das CNHs e comprovantes de residência dos condutores.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Não especificado, mas a isenção é total e não proporcional, sugerindo que é permanente enquanto as condições se mantiverem.",
    "observacoes": "A isenção do IPVA é total, não proporcional. O pedido é feito exclusivamente pela internet, através do Sistema Integrado de Administração da Receita Estadual (SIARE).",
    "fonte_consultada": "https://www.mg.gov.br/servico/solicitar-isencao-do-imposto-sobre-propriedade-de-veiculos-automotores-ipva | https://www.fazenda.mg.gov.br/empresas/impostos/ipva/isencao-de-ipva-para-veiculos/docisencaoipvapcd.html | https://www.agenciaminas.mg.gov.br/noticia/governo-de-minas-aumenta-limite-de-isencao-de-icms-e-ipva-de-veiculo-para-pessoa-com-deficiencia"
  },
  "PA": {
    "nome": "Pará",
    "legislacao": "Instrução Normativa nº 04, de 25 de março de 2015, alterada pela Instrução Normativa nº 33, de 29 de dezembro de 2020 e Instrução Normativa nº 4, de 16 de janeiro de 2024.",
    "teto_veiculo_novo": "Não encontrado nas fontes oficiais consultadas.",
    "teto_veiculo_usado": "Não encontrado nas fontes oficiais consultadas.",
    "deficiencias_aceitas": "Física, Visual, Mental severa ou profunda, Síndrome de Down, Autismo",
    "aceita_nao_condutor": "Sim com condições",
    "orgao_responsavel": "Secretaria de Estado da Fazenda (SEFA-PA)",
    "documentos_exigidos": "1. Documento de identificação e de inscrição no Cadastro de Pessoa Física (CPF) | 2. Certificado de Registro de Veículo (CRV) ou nota fiscal do veículo | 3. Laudo de perícia médica emitido por entidade credenciada pelo DETRAN/PA | 4. Carteira Nacional de Habilitação do requerente ou dos condutores autorizados (limite de 3) | 5. Decisão judicial ou documento que determine a tutela ou curatela, quando for o caso.",
    "passo_a_passo": "1. Formalizar requerimento dirigido ao Secretário de Estado da Fazenda, exclusivamente no Portal de Serviços da SEFA (http://www.sefa.pa.gov.br) | 2. Anexar a documentação exigida.",
    "link_oficial": "http://www.sefa.pa.gov.br",
    "sistema_protocolo": "Portal de Serviços da Sefa (possivelmente integrado ao SIVEI)",
    "link_protocolo": "https://agenciapara.com.br/noticia/24387/sefa-amplia-atendimento-eletronico-nos-processos-de-isencao-de-ipva",
    "condicoes_nao_condutor": "Indicar condutor autorizado, laudo médico em dia, regularidade cadastral e/ou fiscal. O responsável ou tutor deve apresentar laudo médico que comprove a deficiência, além de documentos pessoais do beneficiário e do condutor.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Não encontrado nas fontes oficiais consultadas.",
    "observacoes": "A isenção para não condutores é permitida, com a indicação de até 3 condutores autorizados. O pedido de isenção deve ser feito antes do vencimento do imposto.",
    "fonte_consultada": "https://www.legisweb.com.br/legislacao/?legislacao=282413"
  },
  "PB": {
    "nome": "Paraíba",
    "legislacao": "Lei Nº 13667 DE 15/05/2025 (Altera a Lei Nº 11007/2017)",
    "teto_veiculo_novo": "R$ 120.000 (isenção total até R$ 70.000, parcial entre R$ 70.000 e R$ 120.000)",
    "teto_veiculo_usado": "R$ 120.000 (isenção total até R$ 70.000, parcial entre R$ 70.000 e R$ 120.000)",
    "deficiencias_aceitas": "Física, Visual, Mental severa ou profunda, Síndrome de Down, Autismo",
    "aceita_nao_condutor": "Sim com condições",
    "orgao_responsavel": "SEFAZ-PB",
    "documentos_exigidos": "CPF/CNPJ/Comprovante de Residência | CRLV | Laudo médico ou autorização de compra do ICMS | CNH (se condutor) | Requerimento padrão",
    "passo_a_passo": "1. Enviar os documentos necessários em PDF para gerencia.itcd.ipva@sefaz.pb.gov.br | 2. A guia será liberada após o envio dos documentos",
    "link_oficial": "https://detran.pb.gov.br/noticias/detran-pb-lanca-servico-on-line-para-emissao-de-guia-de-isencao-do-ipva",
    "sistema_protocolo": "E-mail e Atendimento Presencial",
    "link_protocolo": "https://www.sefaz.pb.gov.br/cidadao/ipva#documenta%C3%A7%C3%A3o-necess%C3%A1ria",
    "condicoes_nao_condutor": "Poderá indicar, diretamente ou por meio de seu representante legal, até 3 (três) condutores autorizados, sendo permitida a substituição destes, com indicação de novos condutores, desde que informe esse fato à autoridade competente.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Anual (necessário requerimento no ano anterior)",
    "observacoes": "A isenção é total para veículos até R$ 70.000 e parcial para veículos entre R$ 70.000 e R$ 120.000. O conceito de deficiência será definido no Regulamento do IPVA. É necessário o requerimento de isenção no ano anterior e o beneficiário não pode ter débitos com a Fazenda.",
    "fonte_consultada": "https://www.legisweb.com.br/legislacao/?legislacao=478157 | https://paraiba.pb.gov.br/noticias/em-vigor-governo-da-paraiba-eleva-para-120-mil-valor-da-compra-de-veiculo-destinado-a-pessoa-com-deficiencia-pcd | https://cartaservico.sefaz.pb.gov.br/saibamais.php?id=19 | https://paraiba.pb.gov.br/noticias/prazo-final-de-requerer-isencao-do-ipva-para-2025-vai-ate-31-de-dezembro | https://detran.pb.gov.br/noticias/detran-pb-lanca-servico-on-line-para-emissao-de-guia-de-isencao-do-ipva"
  },
  "PR": {
    "nome": "Paraná",
    "legislacao": "Resolução SEFA nº 135/2021, Art. 17, V (regulamenta a Lei nº 14.260/2003)",
    "teto_veiculo_novo": "Não há teto de valor em reais, mas o veículo deve ter motor de potência não superior a 155 CV",
    "teto_veiculo_usado": "Não há teto de valor em reais, mas o veículo deve ter motor de potência não superior a 155 CV",
    "deficiencias_aceitas": "Física, Visual, Mental severa ou profunda, Síndrome de Down, Autismo",
    "aceita_nao_condutor": "Sim",
    "orgao_responsavel": "Secretaria de Estado da Fazenda (SEFAZ-PR) / Receita Estadual",
    "documentos_exigidos": "Laudo médico do beneficiário (emitido pelo Detran-PR para condutores com deficiência física ou visual; expedido por serviço médico oficial ou entidade conveniada ao SUS para não condutores com deficiência física ou visual, mental severa ou profunda, Síndrome de Down ou autismo)|Documentos pessoais do beneficiário e do proprietário do veículo (se for diferente)",
    "passo_a_passo": "1. Acessar o Portal IPVA|2. Fazer login com a senha do cadastro do programa Nota Paraná ou do sistema Receita/PR|3. Escolher a opção Serviços -> Isenção/Imunidade|4. Selecionar o serviço pretendido, informar os dados solicitados e seguir as orientações até concluir o processo",
    "link_oficial": "https://sped.fazenda.pr.gov.br/servicos/Cidadao/IPVA/Solicitar-Isencao-imunidade-de-IPVA-WaowAd3D",
    "sistema_protocolo": "Portal IPVA (com login Nota Paraná ou Receita/PR)",
    "link_protocolo": "https://www.contribuinte.fazenda.pr.gov.br/ipva/faces/home",
    "condicoes_nao_condutor": "Apresentar documentos pessoais do beneficiário e do proprietário do veículo (se diferentes); potência do motor não superior a 155 CV.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Não especificado na fonte, mas a isenção é concedida a partir da data de início da incapacidade indicada no laudo médico.",
    "observacoes": "O benefício é limitado a um veículo por beneficiário. O veículo deve ter motor de potência não superior a 155 CV. O sistema verifica automaticamente a data de início da concessão de isenção, conforme laudo médico. Em caso de indeferimento, o contribuinte pode solicitar reconsideração.",
    "fonte_consultada": "https://www.fazenda.pr.gov.br/Noticia/Pessoas-com-deficiencia-autismo-ou-Sindrome-de-Down-sao-isentas-de-IPVA | https://sped.fazenda.pr.gov.br/servicos/Cidadao/IPVA/Solicitar-Isencao-imunidade-de-IPVA-WaowAd3D | https://www.sefanet.pr.gov.br/dados/SEFADOCUMENTOS/101202100135.pdf"
  },
  "PE": {
    "nome": "Pernambuco",
    "legislacao": "LEI Nº 10.849/1992, Art.13-C | Decreto 55.937/2023, Art. 10 e Art. 11",
    "teto_veiculo_novo": "R$ 120.000",
    "teto_veiculo_usado": "R$ 70.000 (para benefício integral)",
    "deficiencias_aceitas": "Física (que incapacite três ou quatro dos membros superiores ou inferiores, impossibilitando adaptação do veículo), Visual (cegueira legal), Mental severa ou profunda, Autismo",
    "aceita_nao_condutor": "Sim com condições",
    "orgao_responsavel": "SEFAZ-PE (processamento do pedido) | DETRAN-PE (laudo médico)",
    "documentos_exigidos": "1. Requerimento de Isenção de IPVA | 2. Nota fiscal do veículo (para veículo novo) | 3. Documento de Arrecadação Estadual do IPVA (DAE), gerado no momento de emplacamento do veículo (para veículo novo) | 4. Cópia do documento do veículo (para veículo usado) | 5. Laudo médico fornecido pelo Detran-PE | 6. Comprovante de disponibilidade financeira ou patrimonial (declaração de IRPF ou comprovante de rendimento) do portador da deficiência física, ou do seu cônjuge ou companheiro em união estável, ou dos seus ascendentes, ou dos seus descendentes ou de seus irmãos | 7. CNH do condutor (se o beneficiário for apto a dirigir) | 8. Comprovante de residência do beneficiário | 9. Formulário de identificação dos condutores autorizados (se o beneficiário for inapto a dirigir) | 10. CNH dos condutores autorizados (se o beneficiário for inapto a dirigir) | 11. Comprovante de residência dos condutores autorizados (se o beneficiário for inapto a dirigir) | 12. Documento que comprove o parentesco (se a disponibilidade financeira for de parente) | 13. RG ou certidão de nascimento (se o PCD for menor de idade e os pais forem os requerentes) | 14. Documento que comprove a representação legal (se o PCD tiver representante legal) | 15. Procuração assinada e documento de identificação do despachante (se o processo for feito por despachante)",
    "passo_a_passo": "1. Obter laudo médico expedido pelo DETRAN-PE (seja apto ou inapto a dirigir) | 2. Consultar lista de documentos necessários, preenchê-los e digitalizá-los (formato PDF) | 3. Solicitar a isenção através do Portal de Atendimento da SEFAZ-PE (https://atendimento.sefaz.pe.gov.br/), selecionando a opção Veículos e depois o serviço correspondente | 4. Consultar o andamento da solicitação no Portal de Atendimento da SEFAZ-PE, selecionando a opção VEÍCULOS e depois MINHAS SOLICITAÇÕES. Para veículo novo, a solicitação deve ser feita no momento do emplacamento.",
    "link_oficial": "https://atendimento.sefaz.pe.gov.br/",
    "sistema_protocolo": "Portal de Atendimento",
    "link_protocolo": "https://atendimento.sefaz.pe.gov.br/",
    "condicoes_nao_condutor": "Necessário preencher formulário de identificação de condutores autorizados, apresentar CNH e comprovante de residência dos condutores. O veículo pode ser registrado em nome do responsável. Comprovação de vínculo familiar para disponibilidade financeira.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Anual, de forma automática, caso o sujeito passivo esteja adimplente em relação a qualquer débito referente ao IPVA de sua responsabilidade.",
    "observacoes": "A isenção é limitada a um veículo por beneficiário. O veículo deve ter potência menor ou igual a 2.000 cilindradas. O benefício somente é concedido se o proprietário do veículo estiver adimplente em relação a qualquer débito de IPVA de sua responsabilidade. A solicitação de isenção para veículo usado deve ser feita no exercício seguinte se o veículo foi adquirido após o primeiro dia útil do ano.",
    "fonte_consultada": "https://www.sefaz.pe.gov.br/Servicos/IPVA/Paginas/Isencao_ICMS_IPVA_PCD.aspx | https://www.detran.pe.gov.br/isencao-para-nao-condutor-pessoa-com-deficiencia"
  },
  "PI": {
    "nome": "Piauí",
    "legislacao": "Lei nº 4.548/1992, Art. 5º, VII, e Instrução Normativa UNATRI/SEFAZ Nº 001/2021 (com alterações da IN UNATRI Nº 1/2022)",
    "teto_veiculo_novo": "Não há um teto de valor especificado na legislação vigente.",
    "teto_veiculo_usado": "Não se aplica",
    "deficiencias_aceitas": "Física",
    "aceita_nao_condutor": "Não",
    "orgao_responsavel": "SEFAZ-PI (Secretaria da Fazenda do Estado do Piauí)",
    "documentos_exigidos": "1. Requerimento preenchido e assinado (conforme Anexo VIII da Instrução Normativa UNATRI/SEFAZ Nº001/2021) | 2. Certificado de Registro e Licenciamento de Veículos (CRLV) ou Nota Fiscal de aquisição e Laudo de Vistoria do DETRAN (para veículos novos) | 3. Nota Fiscal de adaptação do veículo (se aplicável) | 4. Carteira Nacional de Habilitação (CNH) com as restrições e adaptações necessárias | 5. Laudo de perícia médica fornecido pelo DETRAN-PI | 6. Comprovante de residência | 7. Certidão de Situação Fiscal e Tributária e Certidão Negativa da Dívida Ativa (emitidas no site da SEFAZ-PI)",
    "passo_a_passo": "1. Acessar o portal SIATweb da SEFAZ-PI | 2. Clicar em 'Processo Eletrônico Tributário' | 3. Clicar em 'Protocolo Eletrônico' | 4. Selecionar 'Abertura de Processo – Público' | 5. Escolher o tipo de assunto 'Benefício para veículos automotores' | 6. Selecionar o assunto correspondente à isenção para PCD | 7. Preencher o requerimento e anexar os documentos exigidos.",
    "link_oficial": "https://siatweb.sefaz.pi.gov.br/processo-eletronico/abertura-processo-publico/",
    "sistema_protocolo": "SIATweb (via 'Processo Eletrônico Tributário' e 'Protocolo Eletrônico')",
    "link_protocolo": "https://www.pi.gov.br/solicitacao-de-isencao-do-ipva-2026-pode-ser-feita-pelo-site-da-sefaz-veja-quem-tem-direito/",
    "condicoes_nao_condutor": "Não se aplica para a legislação vigente em 2026. Projeto de lei para 2027 prevê inclusão de não-condutores como pais ou responsáveis.",
    "tea_nao_condutor": "Não. Projeto de lei para 2027 prevê inclusão de TEA/autismo como não-condutor.",
    "prazo_renovacao": "Vinculado à validade do laudo médico e da CNH. Se o laudo atestar incapacidade permanente, a renovação não é anual, mas é exigido novo laudo na renovação da CNH.",
    "observacoes": "A legislação atual é restrita a deficientes físicos que são condutores e exige adaptação veicular. Um novo projeto de lei foi aprovado para ampliar o benefício (teto de R$ 200.000, incluir outras deficiências e não-condutores), mas as novas regras só devem valer a partir de 2027.",
    "fonte_consultada": "https://www.legisweb.com.br/legislacao/?id=428286"
  },
  "RJ": {
    "nome": "Rio de Janeiro",
    "legislacao": "Lei nº 2.877/1997, Art. 5º, V",
    "teto_veiculo_novo": "R$ 55.000",
    "teto_veiculo_usado": "R$ 70.000",
    "deficiencias_aceitas": "Física, Visual, Intelectual, Autismo",
    "aceita_nao_condutor": "Sim com condições",
    "orgao_responsavel": "Secretaria de Estado de Fazenda (SEFAZ-RJ)",
    "documentos_exigidos": "1. Requerimento de isenção de IPVA | 2. Laudo de avaliação para isenção de IPVA emitido por médico do SUS ou conveniado | 3. CNH do condutor | 4. CPF e RG do proprietário e do condutor | 5. Comprovante de residência | 6. CRLV do veículo | 7. Nota fiscal do veículo (para 0km) | 8. Declaração de que não possui outro veículo com isenção",
    "passo_a_passo": "1. Reunir a documentação necessária | 2. Pagar a Taxa de Serviços Estaduais (TSE) | 3. Abrir processo eletrônico no Sistema Eletrônico de Informações (SEI-RJ) | 4. Anexar os documentos digitalizados | 5. Acompanhar o andamento do processo pelo SEI-RJ",
    "link_oficial": "https://www.portalsei.rj.gov.br/usuarioexterno",
    "sistema_protocolo": "SEI",
    "link_protocolo": "https://sei.rj.gov.br/sip/login.php?sigla_orgao_sistema=ERJ&sigla_sistema=SEI&infra_url=L3NlaS8=",
    "condicoes_nao_condutor": "Após fazer prova do preenchimento das condições e requisitos legais em requerimento devidamente instruído, e encaminhado à autoridade administrativa juntamente com o comprovante do pagamento da Taxa de Serviços Estaduais (TSE). O veículo deve estar em nome da PCD ou de seu representante legal.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "A cada 2 anos",
    "observacoes": "O valor do veículo novo (R$ 55.000) é considerado já com os descontos de IPI e ICMS. Para veículos novos importados, o teto é de R$ 70.000.",
    "fonte_consultada": "https://portal.fazenda.rj.gov.br/ipva/orientacoes-ao-contribuinte/"
  },
  "RN": {
    "nome": "Rio Grande do Norte",
    "legislacao": "Lei Estadual nº 6.967/1996 (alterada pela Lei Estadual nº 10.464/2018), Decreto Estadual nº 18.773/2005, Portaria SEI Nº 699/2020/SET, Decreto nº 29.421/2024",
    "teto_veiculo_novo": "R$ 120.000 (isenção total)",
    "teto_veiculo_usado": "R$ 120.000 (isenção total)",
    "deficiencias_aceitas": "Física, Visual, Auditiva, Mental severa ou profunda, Autismo/TEA",
    "aceita_nao_condutor": "Sim com condições",
    "orgao_responsavel": "SEFAZ-RN (Unidades Regionais de Tributação), DETRAN/RN (Junta Médica)",
    "documentos_exigidos": "1. Requerimento de isenção (Anexo I) | 2. Cópia da CNH válida (se condutor) com indicação da deficiência ou CNH dos condutores autorizados (se não condutor) | 3. Procuração específica (se houver representante) | 4. Instrumento legal de representação (curatela, tutela, guarda) | 5. RG e CPF do beneficiário | 6. Comprovante de residência do beneficiário e dos condutores autorizados (se não condutor) | 7. Certidão Conjunta Negativa de Débitos Estaduais e Dívida Ativa do RN | 8. Laudo Médico emitido pela Junta Médica do DETRAN/RN (para deficiência física e auditiva) ou por prestador de serviço público/privado de saúde (para visual, mental severa/profunda, autismo) | 9. Documento do veículo (CRLV) | 10. Cópia do DANFE de aquisição (veículos novos) | 11. Notas fiscais de adaptação e serviços (se aplicável) | 12. Laudo de vistoria do DETRAN/RN (se aplicável)",
    "passo_a_passo": "1. Verificar a situação do solicitante quanto a débitos estaduais e pagamentos de taxas do DETRAN/RN. | 2. Obter laudo médico conforme a deficiência (Junta Médica do DETRAN/RN ou prestador de serviço de saúde público/privado). | 3. Preencher o requerimento de isenção (Anexo I) disponível online. | 4. Reunir a documentação necessária. | 5. Protocolar o requerimento e documentos nos setores de Protocolo das Unidades Regionais de Tributação. | 6. Acompanhar o andamento do processo pelo site do SEI.",
    "link_oficial": "http://www.set.rn.gov.br/contentProducao/aplicacao/set_v2/legislacao/enviados/listagem_filtro.asp?assunto=5&assuntoEsp=13",
    "sistema_protocolo": "Unidade Virtual de Tributação (UVT)",
    "link_protocolo": "https://uvt.set.rn.gov.br/",
    "condicoes_nao_condutor": "Indicação de até 3 condutores autorizados com domicílio fiscal no mesmo município do beneficiário (exceto vínculo empregatício), vínculo familiar ou empregatício com o beneficiário/responsável legal, ou responsabilidade legal pelo beneficiário, e CNH válida.",
    "tea_nao_condutor": "Sim com condições (incapacidade total para dirigir veículo automotor deve ser declarada pelo responsável legal)",
    "prazo_renovacao": "O prazo de validade do laudo médico é o previsto no laudo emitido pelo DETRAN/RN. Para TEA, o laudo tem prazo indeterminado. A isenção em si não tem prazo de renovação especificado, mas está vinculada à validade do laudo e à adimplência fiscal.",
    "observacoes": "É necessário que o proprietário esteja adimplente com as parcelas de IPVA e todas as taxas do DETRAN/RN, não só do veículo em questão, mas de todos os veículos de sua propriedade. O direito à isenção ocorre a partir da data da entrada do processo, de forma proporcional aos meses vincendos.",
    "fonte_consultada": "https://mundodoautomovelparapcd.com.br/wp-content/uploads/2023/10/ipva-orientacoes-isencao-ipva.pdf | https://www.legisweb.com.br/legislacao/?id=29431 | https://leisestaduais.com.br/rn/lei-ordinaria-n-10464-2018-rio-grande-do-norte-dispoe-sobre-a-inclusao-das-pessoas-com-deficiencia-fisica-visual-mental-severa-ou-profunda-ou-autistas-os-beneficios-alusivos-a-isencao-de-ipva-na-aquisicao-de-veiculos-automotores-alterando-a-lei-estadual-n%C2%BA-6967-de-30-de-dezembro-de-1996-que-dispoe-sobre-o-imposto-de-propriedade-de-veiculos-automotores-ipva"
  },
  "RS": {
    "nome": "Rio Grande do Sul",
    "legislacao": "Lei Estadual 8.115/85, Art. 4º, VI; Decreto 32.144/85, Art. 4°, Inciso VI; § 13 e 14; Instrução Normativa DRP Nº 045/98, Título II, Capítulo III, 1.0, 1.2.2 , “c”; Convênio ICMS 38/12.",
    "teto_veiculo_novo": "R$144.294,68",
    "teto_veiculo_usado": "R$138.200,22",
    "deficiencias_aceitas": "Física, Visual, Mental Severa ou Profunda, Autismo",
    "aceita_nao_condutor": "Sim",
    "orgao_responsavel": "Receita Estadual",
    "documentos_exigidos": "1. Formulário de solicitação de Isenção IPVA | 2. Comprovante de assinatura do requerente (documento de identificação) | 3. Comprovante da capacidade de representação do procurador/responsável | 4. Laudo médico conforme a deficiência (DETRAN/RS para física, laudo de perícia médica para visual, laudo de avaliação médico e psicólogo para autismo e mental severa ou profunda)",
    "passo_a_passo": "Acesse o serviço no Portal Pessoa Física - PPF, em “Serviços Disponíveis”: Menu: \"Veículos - Isenção de IPVA\", Serviço: \"Solicitação de Isenção de IPVA - Pessoa com Deficiência (PcD) - Condutor; ou \"Solicitação de Isenção de IPVA - Pessoa com Deficiência (PcD) - Não Condutor\". A Receita Estadual avisará da decisão através de e-mail e SMS.",
    "link_oficial": "https://www.rs.gov.br/carta-de-servicos/servicos?servico=1890",
    "sistema_protocolo": "Portal e-CAC ou Portal Pessoa Física da Receita Estadual",
    "link_protocolo": "https://atendimento.receita.rs.gov.br/pessoa-fisica/servicos?servico=1890",
    "condicoes_nao_condutor": "O veículo deve ser utilizado em benefício da pessoa com deficiência.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Não especificado (a isenção é concedida para o exercício em que o veículo possua registro em nome do beneficiário desde o primeiro dia do ano para veículos usados, e na data de aquisição para veículos novos. Não há menção de renovação anual ou periódica explícita, mas sim da necessidade de registro no nome do PCD no início do ano para usados).",
    "observacoes": "A isenção é limitada a um veículo por beneficiário. Para veículos usados, a isenção somente poderá ser solicitada a partir de 01 de janeiro do exercício seguinte ao da aquisição, se esta ocorrer após 01 de janeiro. A deficiência visual prevista na legislação que concede o direito à isenção do IPVA é de tal gravidade que impossibilita a obtenção da CNH. Visão monocular não atende aos requisitos para a concessão da isenção do imposto.",
    "fonte_consultada": "https://www.rs.gov.br/carta-de-servicos/servicos?servico=1890"
  },
  "RO": {
    "nome": "Rondônia",
    "legislacao": "Artigos 7º e 14-A do Regulamento do IPVA, instituído pelo Decreto n.º 9.963/2002",
    "teto_veiculo_novo": "R$ 120.000",
    "teto_veiculo_usado": "Mesmo teto (R$ 120.000)",
    "deficiencias_aceitas": "Física, Visual, Mental, Síndrome de Down, Autismo",
    "aceita_nao_condutor": "Sim com condições",
    "orgao_responsavel": "SEFIN - Secretaria de Estado de Finanças",
    "documentos_exigidos": "1. Cópia de documento oficial com foto e CPF do requerente (interessado, curador, tutor ou responsáveis)|2. Cópia de comprovante de residência em Rondônia do interessado|3. Recolhimento da taxa de serviço, no valor de 1 (uma) Unidade Padrão Fiscal de Rondônia (UPF/RO)|4. Na hipótese de representação (procurador), o respectivo instrumento particular com firma reconhecida em cartório, ou o mandato de procuração pública, acompanhado da cópia do documento oficial de identificação pessoal|5. Laudo de perícia médica fornecido pelo Departamento de Trânsito do Estado – DETRAN, no caso de o deficiente ser o condutor do veículo, com especificação da deficiência física e discriminação das características específicas necessárias para que o motorista com deficiência física dirija o veículo|6. Laudo de avaliação que ateste a deficiência física ou visual, quando o beneficiário não for o condutor do veículo, emitido por médico prestador de serviço público de saúde; serviço privado de saúde, contratado ou conveniado, que integre o Sistema Único de Saúde - SUS, acompanhado de declaração que afirme essa condição; ou serviço privado de saúde|7. Laudo de avaliação emitido em conjunto por médico e psicólogo, seguindo os critérios de diagnósticos constantes na Portaria Interministerial n.º 2, de novembro de 2003, do Ministério de Estado da Saúde e do Secretário Especial dos Direitos Humanos, ou outra que a substitua, no caso de pessoa com deficiência mental severa ou profunda, ou autismo, emitido por prestador de serviço público de saúde; serviço privado de saúde, contratado ou conveniado, que integre o Sistema Único de Saúde - SUS, acompanhado de declaração que afirme essa condição; ou serviço privado de saúde|8. Laudo de avaliação emitido por médico que ateste a condição de pessoa com síndrome de Down, emitido por prestador de serviço público de saúde; serviço privado de saúde, contratado ou conveniado, que integre o Sistema Único de Saúde - SUS, acompanhado de declaração que afirme essa condição; ou serviço privado de saúde|9. Cópia da Carteira Nacional de Habilitação, na qual constem as restrições ao condutor e as adaptações necessárias ao veículo, quando o motorista do veículo for o portador da deficiência física|10. Cópia da Carteira Nacional de Habilitação de todos os condutores autorizados, se houver indicação",
    "passo_a_passo": "1. Acessar o sistema e-PAT (https://epat.sefin.ro.gov.br/)|2. Realizar login no e-PAT|3. No canto esquerdo clicar em “Abrir um Processo”|4. Selecionar o tipo de processo “ISENÇÃO DE IPVA PARA PCD”|5. Preencher o formulário eletrônico e anexar a documentação necessária|6. Acompanhar o processo pelo e-PAT",
    "link_oficial": "https://portaldocidadao.ro.gov.br/Servico/Detalhes?id=4a3e95de-5179-4b16-5d1a-08dd025d9d3b",
    "sistema_protocolo": "e-PAT",
    "link_protocolo": "https://epat.sefin.ro.gov.br/",
    "condicoes_nao_condutor": "Indicar no máximo 3 condutores autorizados, que comprovem residência na mesma localidade do beneficiário. Substituição permitida mediante novo laudo pericial.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Não especificado, mas a isenção é concedida integralmente para veículos até R$ 120.000,00",
    "observacoes": "Não será concedida a isenção se o beneficiário possuir débitos vencidos e não pagos junto à Fazenda Pública Estadual. A taxa para solicitar a isenção é de 01 (uma) Unidade de Padrão Fiscal de Rondônia (UPF/RO).",
    "fonte_consultada": "https://portaldocidadao.ro.gov.br/Servico/Detalhes?id=4a3e95de-5179-4b16-5d1a-08dd025d9d3b"
  },
  "RR": {
    "nome": "Roraima",
    "legislacao": "Decreto nº 1.083/1995 (Regulamento do IPVA)",
    "teto_veiculo_novo": "Não especificado na legislação encontrada.",
    "teto_veiculo_usado": "Não especificado na legislação encontrada.",
    "deficiencias_aceitas": "Física, Visual, Mental, Autismo",
    "aceita_nao_condutor": "Sim com condições (designar até 3 condutores autorizados)",
    "orgao_responsavel": "SEFAZ-RR (Secretaria de Estado da Fazenda de Roraima)",
    "documentos_exigidos": "1. Cópia do RG e CPF ou da Carteira Nacional de Habilitação (CNH) do Portador de Doenças Graves ou do condutor autorizado | 2. Laudo Médico original expedido pelo DETRAN, ou por clínica por este credenciada | 3. Cópia de Comprovante de Residência | 4. Cópia da Nota Fiscal de aquisição do bem, quando se tratar de veículo novo | 5. Comprovante original de recolhimento da Taxa de Expediente | 6. Cópia da CNH do(s) condutor(es) autorizado(s), se houver",
    "passo_a_passo": "1. Reunir todos os documentos exigidos, incluindo os formulários de requerimento, laudos médicos e identificação de condutores, disponíveis no portal da SEFAZ-RR. | 2. Preencher os formulários. | 3. Protocolar o pedido nas Agências de Rendas da jurisdição do requerente.",
    "link_oficial": "https://www.sefaz.rr.gov.br/cidadao/downloads/category/414-01-ipva-pessoa-com-deficiencia-pcd",
    "sistema_protocolo": "SEI",
    "link_protocolo": "https://sei.rr.gov.br/portalsei/",
    "condicoes_nao_condutor": "Designar até 3 condutores autorizados, conforme identificação e modelo disponibilizado no sítio eletrônico oficial da SEFAZ.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "O laudo médico tem validade de 1 ano, sugerindo a necessidade de renovação anual do benefício.",
    "observacoes": "A legislação específica sobre isenção para PCD (Lei 1.293/2018 e Decreto 29.347-E/2020) foi declarada inconstitucional pelo STF e posteriormente revogada. A isenção parece seguir as regras gerais do Regulamento do IPVA, que é mais antigo e menos detalhado.",
    "fonte_consultada": "https://www.sefaz.rr.gov.br/cidadao/downloads/category/414-01-ipva-pessoa-com-deficiencia-pcd"
  },
  "SC": {
    "nome": "Santa Catarina",
    "legislacao": "Regulamento do IPVA (RIPVA/SC), aprovado pelo Decreto nº 2.884/1989, Art. 6º, inciso IV, alíneas 'e' e 'm'",
    "teto_veiculo_novo": "Sem limite de valor, mas com motor de cilindrada não superior a 2.000 cm³ para não condutores.",
    "teto_veiculo_usado": "Mesmo teto do veículo novo.",
    "deficiencias_aceitas": "Física, Visual, Mental Severa ou Profunda, Autismo",
    "aceita_nao_condutor": "Sim",
    "orgao_responsavel": "Secretaria de Estado da Fazenda (SEF/SC)",
    "documentos_exigidos": "1. Documento de propriedade do veículo | 2. Documento de identificação do beneficiário | 3. Documento de identificação do representante legal (quando for o caso) | 4. Documento que comprove que o signatário seja o representante legal do portador da deficiência ou autista (quando for o caso) | 5. CNH do beneficíario (para condutores) ou do(s) condutor(es) (para não condutores) | 6. Comprovante de residência | 7. Laudo de avaliação emitido por prestador de serviço de saúde do SUS | 8. Declaração de que o prestador de serviço é integrante do SUS | 9. Declaração de destinação do veículo ao uso do portador de deficiência",
    "passo_a_passo": "1. Acessar o site da SEF (www.sef.sc.gov.br) e seguir para a seção de IPVA > Isenções | 2. Iniciar o pedido no sistema SAT, informando o CPF do beneficiário | 3. Preencher os dados de contato e do requerimento | 4. Anexar todos os documentos digitalizados em formato PDF | 5. Gerar e pagar a DARE da taxa de serviços | 6. Enviar o processo para análise da SEF | 7. Acompanhar o andamento do pedido online com o número de protocolo",
    "link_oficial": "https://www.sef.sc.gov.br/servicos/solicitar-isencao-ou-imunidade-de-ipva-pessoa-com-deficiencia-ou-autista",
    "sistema_protocolo": "SAT (Sistema de Administração Tributária) / TTD (Tratamento Tributário Diferenciado)",
    "link_protocolo": "https://www.sef.sc.gov.br/servicos/solicitar-isencao-ou-imunidade-de-ipva-pessoa-com-deficiencia-ou-autista",
    "condicoes_nao_condutor": "CNH do condutor autorizado - 1 condutor- obrigatório para pessoa com deficiência ou autista não condutor(a).",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Indeterminado, enquanto as condições forem mantidas.",
    "observacoes": "A isenção para não condutores se aplica a veículos com motor de cilindrada não superior a 2.000 cm³. O laudo de avaliação tem validade por prazo indeterminado.",
    "fonte_consultada": "https://www.sef.sc.gov.br/arquivos_portal/servicos/54/MANUAL_GUIA___PEDIDOS_DE_ISENC%C3%83O_DE_IPVA_PARA_PESSOAS_COM_DEFICI%C3%8ANCIA_E_AUTISTAS___TTD_596.pdf"
  },
  "SP": {
    "nome": "São Paulo",
    "legislacao": "Convênio ICMS 38/2012 (e alterações), Portaria CAT 27/2015 (e alterações)",
    "teto_veiculo_novo": "R$ 70.000 (isenção total), R$ 120.000 (isenção parcial)",
    "teto_veiculo_usado": "R$ 70.000 (isenção total), R$ 120.000 (isenção parcial)",
    "deficiencias_aceitas": "Transtorno do espectro do autismo em grau moderado, grave ou gravíssimo, Deficiência física, sensorial, intelectual ou mental, moderada, grave ou gravíssima",
    "aceita_nao_condutor": "Sim com condições (comprovação do grau de deficiência ou TEA e indicação de até 2 condutores autorizados)",
    "orgao_responsavel": "Secretaria da Fazenda e Planejamento do Estado de São Paulo (SIVEI)",
    "documentos_exigidos": "1. Laudo pericial regulamentado pelo IMESC | 2. CPF e RG da PCD, representante legal e condutores autorizados | 3. CNH da PCD (se condutora), representante legal e condutores autorizados | 4. Comprovantes de endereço da PCD, representante legal e condutores autorizados | 5. CRV, CRLV ou Formulário Renavam | 6. Autorização para até 2 condutores (SIVEI) | 7. Declaração de não possuir outro veículo com isenção (SIVEI) | 8. Documento que comprove a representação legal (se for o caso) | 9. Outros documentos solicitados pela autoridade fiscal | 10. Contrato de arrendamento mercantil (se for o caso)",
    "passo_a_passo": "1. Agendar perícia no site do IMESC | 2. Acessar o SIVEI - Sistema de Veículos no Portal da Secretaria da Fazenda e Planejamento | 3. No sistema, selecionar \"Novo Requerimento\", preencher o formulário e carregar os documentos | 4. Aguardar o julgamento do pedido (deferimento ou indeferimento) | 5. Consultar a situação da isenção no SIVEI ou Certidão de Isenção",
    "link_oficial": "https://www3.fazenda.sp.gov.br/SIVEI/",
    "sistema_protocolo": "SIVEI",
    "link_protocolo": "https://www3.fazenda.sp.gov.br/SIVEI/",
    "condicoes_nao_condutor": "Comprovação do grau moderado, grave ou gravíssimo de deficiência ou TEA, aferido em avaliação biopsicossocial. Necessário CNH do condutor PCD ou de até 2 condutores autorizados.",
    "tea_nao_condutor": "Sim com condições",
    "prazo_renovacao": "Anual (sujeito a reavaliação)",
    "observacoes": "Até 31/12/2023 o valor limite para isenção total era de R$100 mil. Para veículos entre R$70.000 e R$120.000, a isenção é parcial, sendo o imposto devido sobre o valor que excede R$70.000. Para veículos acima de R$120.000, não há isenção.",
    "fonte_consultada": "https://portal.fazenda.sp.gov.br/servicos/ipva/Paginas/como-solicitar-isencao-ipva-pcd.aspx"
  },
  "SE": {
    "nome": "Sergipe",
    "legislacao": "Lei nº 9.517/2024 (altera e revoga dispositivos da Lei nº 7.655/2013) e Decreto nº 29684/2014",
    "teto_veiculo_novo": "R$ 70.000,00 (isenção total) ou R$ 120.000,00 (isenção parcial)",
    "teto_veiculo_usado": "R$ 70.000,00 (isenção total) ou R$ 120.000,00 (isenção parcial)",
    "deficiencias_aceitas": "Física, Visual, Intelectual severa, Síndrome de Down, Autismo",
    "aceita_nao_condutor": "Sim com condições (indicar até 3 condutores autorizados, com possibilidade de substituição, informando à repartição fiscal)",
    "orgao_responsavel": "SEFAZ - Secretaria de Estado da Fazenda",
    "documentos_exigidos": "1. Estar enquadrado na perícia do Detran | 2. Laudo médico do Detran/SE - permanente | 3. CRLV - certificado de registro de licenciamento de veículo (veículo usado) | 4. Carteira Nacional de Habilitação - CNH | 5. Nota fiscal do veículo no valor venal até R$ 70.000,00 (veículo novo) | 6. Taxa de IPVA - Sefaz | Para não condutor: 1. Carteira de habilitação - CNH (Condutor Autorizado) | 2. Documento de Identidade e CPF | 3. CRLV - Certificado de Registro de Licenciamento de Veículo (Veículo Usado) | 4. Laudo de Avaliação Médica e Psicológica - Receita Federal | 5. Documento de Comprovação Representante Legal com os mesmos requisitos do PCD | 6. Taxa de IPVA - Sefaz | 7. Nota fiscal do veículo no valor venal até R$ 70.000,00 (Veículo Novo)",
    "passo_a_passo": "1. Fazer a solicitação através do site oficial | 2. Realizar o pagamento da taxa gerada | 3. Enviar documentação exigida pelo e-doc: https://www.edocsergipe.se.gov.br/protocolo-externo/",
    "link_oficial": "https://www.sefaz.se.gov.br/SitePages/servico.aspx?)cod=1&Url=https%3a//security.sefaz.se.gov.br/internet/publico/cleanProcess.jsp&AppName=SAE&TransId=T29782&CancelUrl=paginaInicial.jsp",
    "sistema_protocolo": "e-doc (Sistema de Protocolo Externo)",
    "link_protocolo": "https://www.edocsergipe.se.gov.br/protocolo-externo/",
    "condicoes_nao_condutor": "Quando inapto a dirigir, laudo médico deve constar esta circunstância, e até 3 condutores autorizados podem ser indicados. Substituição permitida com comunicação à repartição fiscal.",
    "tea_nao_condutor": "Sim com condições (autismo que gera incapacidade de dirigir, atestado por laudo médico e psicológico)",
    "prazo_renovacao": "Anual",
    "observacoes": "A isenção é parcial para veículos entre R$ 70.000,00 e R$ 120.000,00, sendo o IPVA recolhido apenas sobre a parcela restante acima de R$ 70.000,00. A nova medida passa a valer a partir de janeiro de 2025.",
    "fonte_consultada": "https://www.se.gov.br/servicos/212 | https://al.se.leg.br/aprovada-na-alese-lei-assegura-isencao-parcial-do-ipva-para-pcd/"
  },
  "TO": {
    "nome": "Tocantins",
    "legislacao": "Lei nº 4.426/2024, que altera a Lei nº 1.287/2001 (Código Tributário do Estado do Tocantins)",
    "teto_veiculo_novo": "R$ 120.000 (isenção parcial, imposto sobre o que ultrapassar R$ 70.000)",
    "teto_veiculo_usado": "Mesmo teto (isenção parcial, imposto sobre o que ultrapassar R$ 70.000)",
    "deficiencias_aceitas": "Física, Visual, Mental Severa ou Profunda, Surdas ou com Deficiência Auditiva, Síndrome de Down, Autismo (TEA)",
    "aceita_nao_condutor": "Sim",
    "orgao_responsavel": "SEFAZ-TO (Secretaria da Fazenda do Tocantins)",
    "documentos_exigidos": "1. Certificado de Registro e Licenciamento do Veículo (CRLV) ou nota fiscal (veículo novo)|2. RG e CPF do requerente e do representante legal|3. Laudo de Avaliação expedido pelo DETRAN ou clínicas credenciadas (para PCD física)|4. Cópia da Carteira Nacional de Habilitação (CNH) com as restrições referentes ao condutor e às adaptações necessárias ao veículo (para PCD física)|5. Laudo de Avaliação emitido em conjunto por médico e psicólogo (para PCD mental severa ou profunda ou autismo)|6. Taxa de Serviços Estaduais (TSE)|7. Documento que comprove a representação legal",
    "passo_a_passo": "1. Reunir a documentação necessária conforme o tipo de deficiência e se é condutor ou não-condutor|2. Apresentar o pedido de isenção do IPVA na Agência de Atendimento do município de registro do veículo",
    "link_oficial": "https://portal.sefaz.to.gov.br/cidadao",
    "sistema_protocolo": "Atendimento presencial em uma Agência de Atendimento da SEFAZ.",
    "link_protocolo": "https://www.to.gov.br/sefaz",
    "condicoes_nao_condutor": "É necessário apresentar uma autorização que identifique o condutor do veículo.",
    "tea_nao_condutor": "Sim",
    "prazo_renovacao": "Não especificado nas fontes consultadas",
    "observacoes": "A isenção é parcial para veículos novos acima de R$ 70.000,00, sendo o imposto devido apenas sobre o valor que ultrapassar esse teto, até o limite de R$ 120.000,00.",
    "fonte_consultada": "https://www.al.to.leg.br/noticia/14255/governador-sanciona-lei-de-olyntho-que-beneficia-pcds-tocantinenses | https://doe.to.gov.br/diario/5178/download | https://www.instagram.com/p/DHdg7qJOiBN/?hl=en | https://portal.sefaz.to.gov.br/cidadao"
  }
};

export type EstadoIPVAPCD = typeof estadosIPVAPCD[keyof typeof estadosIPVAPCD];

export const listaEstados = Object.entries(estadosIPVAPCD).map(([uf, dados]) => ({
  uf,
  nome: dados.nome
})).sort((a, b) => a.nome.localeCompare(b.nome));
