CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nome` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`telefone` varchar(20) NOT NULL,
	`estado` varchar(2) NOT NULL,
	`estadoNome` varchar(100) NOT NULL,
	`deficiencia` varchar(100) NOT NULL,
	`condutor` varchar(10) NOT NULL,
	`tipoVeiculo` varchar(10) NOT NULL,
	`valorVeiculo` varchar(20) NOT NULL,
	`laudoMedico` varchar(10) NOT NULL,
	`elegivel` boolean NOT NULL DEFAULT false,
	`motivoElegibilidade` text,
	`origem` varchar(50) NOT NULL DEFAULT 'site',
	`utmSource` varchar(100),
	`utmMedium` varchar(100),
	`utmCampaign` varchar(100),
	`contatado` boolean NOT NULL DEFAULT false,
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
